### ISSUE TITLE
Complete draft template for section 2.1-2.1.5

### ISSUE THREAD

**Issue by Ghost-8D** [CS-UCY-EPL343/EPL343.Winter18.Team5#13]
Download the draft from the Moodle and complete the section based on what we know so far. If there are any blank points, contact me. This must be done and uploaded to the repository by Monday, Oct 01 (23.59:59).

**Comment by ghost** [comment]
- [x] 2.1
- [x] 2.1.1
- [x] 2.1.2
- [x] 2.1.3
- [x] 2.1.4
- [x] 2.1.5
