### ISSUE TITLE
Create draft for 3.1-3.2.1 for Specs document 

### ISSUE THREAD

**Issue by Ghost-8D** [CS-UCY-EPL343/EPL343.Winter18.Team5#23]
Create draft for 3.1-3.2.1 for Specs document based on the template from Moodle. Should be uploaded to Github by Sunday 14/10/2018 23:59.

**Comment by andrianiKo** [comment]
We should discuss the use cases. So many options. Changes should be made to Reqs report also..

**Comment by Ghost-8D** [comment]
Tasks should be closed when we have completed the requested part and we have a ready-to-submit version.
