### ISSUE TITLE
Create a presentation for Monday 26/11

### ISSUE THREAD

**Issue by Ghost-8D** [CS-UCY-EPL343/EPL343.Winter18.Team5#68]
On Monday 26/11/2018 between 16:50-16:58 we will have to present (at B121) our Prototype. For this presentation we will have to create a powerpoint document which must include all screens of our application and explain its functionality. We should also report that we created the database.

**Comment by adamos2468** [comment]
Their functionality*

**Comment by Ghost-8D** [comment]
*autocorrect mistake
